spring.application.name=Case-Pessoas

spring.threads.virtual.enabled=true

api.security.client.id=client-id-pessoas
api.security.client.secret=$2a$10$jTy13CLRSoTdpKcWZc237.XWz94W9CcqcN/mHGVNYbttdZj2uDcmC
api.security.token.secret=ChaveAPIpESSOAS1212

spring.datasource.url=jdbc:postgresql://localhost:5432/colaborador_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

logging.level.com.pessoas.Case.Pessoas=DEBUG