spring.application.name=Case-Pessoas

spring.threads.virtual.enabled=true

spring.config.import=optional:aws-secretsmanager:api-pessoas2,optional:aws-secretsmanager:case-pessoas/rds-credentials2

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

spring.flyway.enabled=true

logging.level.com.pessoas.Case.Pessoas=DEBUG


#Rodar Local
#api.security.client.id=client-id-pessoas
#api.security.client.secret=$2a$10$yYPVacTLdG7bbt2ALPPuuejX6ryihYkKpdq3Fs6eTJh11bYmy.tRy
#api.security.token.secret=ChaveAPIpESSOAS1212
#spring.datasource.url=jdbc:postgresql://localhost:5432/colaborador_db
#spring.datasource.username=postgres
#spring.datasource.password=admin